### ISSUE TITLE
KeyPath constructor same library warning

### ISSUE THREAD

**Issue by brittonjg** [airbnb/lottie#26]
When using `KeyPath` I get a warning on Android Studio 3.1 Beta 1, stating that it can only be used within the same library (lottie). Using Lottie version 2.5.0-rc1

![screen shot 2018-02-08 at 09 40 44](https://user-images.githubusercontent.com/12110204/35965904-2dd0f3f4-0cb4-11e8-8099-0209a13bac59.png)

Note, discussed with @gpeal and requested to raise an issue.

**Comment by madamvixen** [comment]
Faced the same issue on a project. 
A very risky work-around, this:
`lintOptions {
     ...
     ignore 'RestrictedApi'
}`

Works for this. But would love to have this issue fixed so I don't have to do ☝️

**Comment by gpeal** [comment]
THis is fixed in 2.5.1

**Comment by Tywholland** [comment]
I still see this issue with 2.5.3. I'm using Android Studio 3.1, and created a fresh project just to test out Lottie and still get the error.

**Comment by gpeal** [comment]
@Tywholland please post this on lottie-android. This is the documentation repo
